config/routes.rb
Railstraining::Application.routes.draw do
  resources :snippets

  get "home/index"

root :to => "home#index"

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
    validates :content, :presence => true
# a title must exist, and its length shall be at least 2 characters.
    validates :title, :presence => true,
		     :length => { :minimum => 2 }
validates_inclusion_of :language, :in => ["cpp", "c", "ruby", "python"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  # GET /snippets
  # GET /snippets.xml
  def index
    @snippets = Snippet.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @snippets }
    end
  end

  # GET /snippets/1
  # GET /snippets/1.xml
  def show
    @snippet = Snippet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @snippet }
    end
  end

  # GET /snippets/new
  # GET /snippets/new.xml
  def new
    @snippet = Snippet.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @snippet }
    end
  end

  # GET /snippets/1/edit
  def edit
    @snippet = Snippet.find(params[:id])
  end

  # POST /snippets
  # POST /snippets.xml
  def create
    @snippet = Snippet.new(params[:snippet])

    respond_to do |format|
      if @snippet.save
        format.html { redirect_to(@snippet, :notice => 'Snippet was successfully created.') }
        format.xml  { render :xml => @snippet, :status => :created, :location => @snippet }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @snippet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /snippets/1
  # PUT /snippets/1.xml
  def update
    @snippet = Snippet.find(params[:id])

    respond_to do |format|
      if @snippet.update_attributes(params[:snippet])
        format.html { redirect_to(@snippet, :notice => 'Snippet was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @snippet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.xml
  def destroy
    @snippet = Snippet.find(params[:id])
    @snippet.destroy

    respond_to do |format|
      format.html { redirect_to(snippets_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/home/index.html.erb
<h1>Hello, rails !</h1>
<%= link_to "Code Snippets", snippets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railstraining</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body style="background: #EEEEEE;">

<%= yield %>

</body>
</html>

app/views/snippets/_form.html.erb
<%= form_for(@snippet) do |f| %>
  <% if @snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
      <% @snippet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.select(:language, [['C++', 'cpp'], ['C', 'c'], ['Python', 'python'], ['Ruby', 'ruby']]) =%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/snippets/edit.html.erb
<h1>Editing snippet</h1>

<%= render 'form' %>

<%= link_to 'Show', @snippet %> |
<%= link_to 'Back', snippets_path %>

app/views/snippets/index.html.erb
<h1>Listing snippets</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Language</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @snippets.each do |snippet| %>
  <tr>
    <td><%= snippet.title %></td>
    <td><%= snippet.content %></td>
    <td><%= snippet.language %></td>
    <td><%= link_to 'Show', snippet %></td>
    <td><%= link_to 'Edit', edit_snippet_path(snippet) %></td>
    <td><%= link_to 'Destroy', snippet, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Snippet', new_snippet_path %>

app/views/snippets/new.html.erb
<h1>New snippet</h1>

<%= render 'form' %>

<%= link_to 'Back', snippets_path %>

app/views/snippets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @snippet.title %>
</p>

<p>
  <b>Content:</b><br/>
  <div class="details">

  <%= 
	require 'rubygems'
	require 'syntax/convertors/html'
	c = Syntax::Convertors::HTML.for_syntax @snippet.language
        highlighted = c.convert(@snippet.content,false)
	highlighted.sub!("/^<pre>§", "<pre class=\"code\">\n")
	highlighted
  %> 
  
  </div>
</p>

<p>
  <b>Language:</b>
  <%= @snippet.language %>
</p>


<%= link_to 'Edit', edit_snippet_path(@snippet) %> |
<%= link_to 'Back', snippets_path %>